-- CREATE TABLE STATEMENTS

CREATE TABLE NOTIFICATION (
	NotificationId INT IDENTITY(1,1) PRIMARY KEY,
	FriendId INT FOREIGN KEY REFERENCES FRIEND(FriendId) NOT NULL,
	NotificationTypeId INT FOREIGN KEY REFERENCES NOTIFICATION_TYPE(NotificationTypeId) NOT NULL,
	SendFrom Bit NOT NULL,
	NotificationDate DATE NOT NULL	 
)

CREATE TABLE NOTIFICATION_TYPE (
	NotificationTypeId INT IDENTITY(1,1) PRIMARY KEY,
	NotificationType nvarchar(50) NOT NULL,
	LinkToView nvarchar(1000) NOT NULL,
	[Message] nvarchar(1000) NOT NULL
)

CREATE TABLE STREET_ADDRESS (
	StreetAddressId INT IDENTITY(1,1) PRIMARY KEY,
	StreetAddress nvarchar(100)
)

CREATE TABLE STATE (
	StateId INT IDENTITY(1,1) PRIMARY KEY,
	StateName nvarchar(30)
)

CREATE TABLE CITY (
	CityID INT IDENTITY(1,1) PRIMARY KEY,
	CityName nvarchar(75)
)

CREATE TABLE ZIPCODE (
	ZipCodeId INT IDENTITY(1,1) PRIMARY KEY,
	ZipCode nvarchar(12)
)

CREATE TABLE ADDRESS (
	AddressId INT IDENTITY(1,1) PRIMARY KEY,
	StreetAddressId INT FOREIGN KEY REFERENCES STREET_ADDRESS(StreetAddressId) NOT NULL,
	CityId INT FOREIGN KEY REFERENCES CITY(CityId) NOT NULL,
	StateId INT FOREIGN KEY REFERENCES STATE(StateId) NOT NULL,
	ZipCodeId INT FOREIGN KEY REFERENCES ZIPCODE(ZipCodeId) NOT NULL
)

CREATE TABLE USER_ADDRESS (
	UserAddressId INT IDENTITY(1,1) PRIMARY KEY,
	AddressId INT FOREIGN KEY REFERENCES [ADDRESS](AddressId) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES[User] NOT NULL,
	IsDefault Bit NOT NULL,
	Alias nvarchar(50)
)

CREATE TABLE FRIEND (
	FriendId INT IDENTITY(1,1) PRIMARY KEY,
	User1Id INT FOREIGN KEY REFERENCES [USER](UserId) NOT NULL,
	User2Id INT FOREIGN KEY REFERENCES [User](UserId) NOT NULL,
	FriendTypeId INT FOREIGN KEY REFERENCES FRIEND_TYPE(FriendTypeId) NOT NULL
)

CREATE TABLE FRIEND_TYPE (
	FriendTypeId INT IDENTITY(1,1) PRIMARY KEY,
	FriendType nvarchar(25) NOT NULL,
	FriendTypeDescr nvarchar(1000)
)