platform :ios, '9.0'
  use_frameworks!

target 'Mito 1.0' do
  pod 'Alamofire', '~> 4.7'
  pod 'Starscream', '~> 3.0.2'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'PayCardsRecognizer'
  pod 'SwiftDate'
end
